name: Flow_Tests

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main
  
jobs:  
  job1:
    runs-on: ubuntu-latest
    steps:
    
    
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:  
        python-version: 3.9
    - name: Common set up
      run: |
         sudo apt-get update 
     
    
    - name: Define IP server
      run: |
          SERV_IP=$(ip -4 addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}') >> $GITHUB_ENV
          echo $SERV_IP
          echo $SERV_IP > math-homework.txt
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v2
      with:
        name: homework
        path: math-homework.txt  

    - name: Set up iperf3
      run: |
          sudo apt-get install -y iperf3
          iperf3 -v
          iperf3 -s -1     
    
          
  build:    
    # needs: job1 
    runs-on: ubuntu-latest
    steps:   
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:  
        python-version: 3.9
    - name: Set up iperf3
      run: |   
        sudo apt-get update
        sudo apt-get install -y iperf3
        ifconfig
    - name: Set up pyATS    
      run: |    
        pip install pyats[full]

    - name: Download math result for job 1
      uses: actions/download-artifact@v2
      with:
        name: homework
    
    - name: GET IP
      run: |
          SERV_IP=$(cat math-homework.txt) >> $GITHUB_ENV
          export IP=$SERV_IP
          echo $IP
          pyats run job py_job.py
    
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: output.json
